version: '3'
services:
  streamlit-app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8501:8501"  # Map port 8501 in the container to port 8501 on the host